name: Run Tosca Tests

on:
  push:
    branches:
      - main

jobs:
  run-tosca-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Executar Testes Tosca
      run: |
        powershell.exe -ExecutionPolicy Bypass -File .\tosca_execution_client.ps1 `
          -toscaServerUrl "http://localhost:8732" `
          -projectName "tosca-expandtesting_api" `
          -events '["1 - check api health - /health-check Request", "1 - check api health - /health-check Response"]' `
          -clientId "${{ secrets.TOSCA_CLIENT_ID }}" `
          -clientSecret "${{ secrets.TOSCA_CLIENT_SECRET }}"


